#!/usr/bin/env node
/**
 * Downloads webfonts from Google Fonts and self-hosts them.
 *
 * Why self-host rather than link to fonts.googleapis.com:
 *  1. GDPR. Linking to Google Fonts sends every visitor's IP to Google without
 *     consent. A German court (LG München, 3 O 17493/20) held that this alone is an
 *     actionable privacy violation. For a Portuguese business serving EU visitors,
 *     self-hosting removes the question entirely.
 *  2. Performance. It drops two cross-origin round trips (CSS, then font) from the
 *     critical path, and cross-site font caching no longer exists in any modern
 *     browser, so the old "it's probably cached already" argument is dead.
 *
 * We request the CSS with a modern Chrome UA so Google returns woff2, then rewrite
 * the src: urls to local paths and keep only the latin + latin-ext subsets
 * (latin-ext carries the Portuguese diacritics).
 *
 * Usage: node scripts/fetch-fonts.js [--force]
 */
const fs = require('fs');
const path = require('path');
const https = require('https');

const FONT_DIR = path.resolve(__dirname, '..', 'src', 'assets', 'fonts');
const CSS_OUT = path.resolve(__dirname, '..', 'src', 'assets', 'css', 'fonts.css');
const FORCE = process.argv.includes('--force');

// A modern UA is required or Google serves legacy ttf/woff instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const FAMILIES = [
  // Space Grotesk for headings and figures. The client asked for modern and clean over
  // the earlier serif direction: a geometric grotesque with just enough character in
  // the terminals to not be Arial, and it reads as precision engineering — which is
  // the right register for a detailing studio. One variable file covers 400..700.
  // Note it ships no italic: emphasis on this site is colour and weight, never slant.
  {
    css: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400..700&display=swap',
    slug: 'space-grotesk',
  },
  // Inter for everything a visitor actually reads or taps: body, nav, labels, buttons.
  // It also carries tabular figures (tnum), which the price table needs — proportional
  // digits make the euro column jitter as the tier changes.
  {
    css: 'https://fonts.googleapis.com/css2?family=Inter:wght@400..700&display=swap',
    slug: 'inter',
  },
  // Rubik italic, exclusively for the brand lockup. The official logo sets
  // "GARAGEM DO BRILHO" in Rubik Bold Italic and "AUTO DETAILING" in Rubik Italic
  // (see src/assets/brand/*.svg — the wordmark is live text, not outlines), so the
  // header wordmark uses the same face or it isn't their logo.
  {
    css: 'https://fonts.googleapis.com/css2?family=Rubik:ital,wght@1,400..700&display=swap',
    slug: 'rubik-italic',
  },
];

function get(url, asBuffer = false) {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { 'User-Agent': UA } }, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          res.resume();
          return resolve(get(res.headers.location, asBuffer));
        }
        if (res.statusCode !== 200) {
          res.resume();
          return reject(new Error(`HTTP ${res.statusCode} for ${url}`));
        }
        const chunks = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => resolve(asBuffer ? Buffer.concat(chunks) : Buffer.concat(chunks).toString('utf8')));
        res.on('error', reject);
      })
      .on('error', reject);
  });
}

/**
 * Google's CSS is a sequence of @font-face blocks, each preceded by a
 * `/* subset *\/` comment. Split on those so we can drop subsets we don't serve.
 */
function parseBlocks(css) {
  const out = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
  let m;
  while ((m = re.exec(css)) !== null) {
    out.push({ subset: m[1], block: m[2] });
  }
  return out;
}

async function main() {
  fs.mkdirSync(FONT_DIR, { recursive: true });
  fs.mkdirSync(path.dirname(CSS_OUT), { recursive: true });

  const chunks = [
    '/* Self-hosted webfonts. GENERATED by scripts/fetch-fonts.js — do not edit by hand. */',
    '',
  ];
  let total = 0;
  const preload = [];

  for (const fam of FAMILIES) {
    const css = await get(fam.css);
    const blocks = parseBlocks(css).filter((b) => KEEP_SUBSETS.has(b.subset));
    if (!blocks.length) throw new Error(`No latin subsets found for ${fam.slug}`);

    for (const { subset, block } of blocks) {
      const urlMatch = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
      if (!urlMatch) continue;

      // Subsets are unique within a family, so the subset name alone is a stable
      // filename — no counter needed.
      const filename = `${fam.slug}-${subset}.woff2`;
      const dest = path.join(FONT_DIR, filename);

      if (!fs.existsSync(dest) || FORCE) {
        const buf = await get(urlMatch[1], true);
        fs.writeFileSync(dest, buf);
        console.log(`  ${filename}  ${(buf.length / 1024).toFixed(1)} KB`);
      }
      total += fs.statSync(dest).size;

      // Only the primary latin subset is preloaded; latin-ext is a progressive
      // enhancement for the diacritics and shouldn't block first paint.
      if (subset === 'latin') preload.push(filename);

      const rewritten = block
        .replace(urlMatch[1], `../fonts/${filename}`)
        // font-display: swap keeps text visible during load (no FOIT). Combined with
        // size-adjust-free metrics this is the smallest-CLS option available here.
        .replace(/font-display:\s*\w+;/, 'font-display: swap;');

      chunks.push(`/* ${fam.slug} · ${subset} */`, rewritten, '');
    }
  }

  fs.writeFileSync(CSS_OUT, `${chunks.join('\n')}\n`);
  fs.writeFileSync(
    path.join(FONT_DIR, 'preload.json'),
    `${JSON.stringify(preload, null, 2)}\n`
  );

  console.log(`\nFonts: ${(total / 1024).toFixed(0)} KB total, ${preload.length} preloaded.`);
  console.log(`CSS written to ${path.relative(process.cwd(), CSS_OUT)}`);
}

main().catch((err) => {
  console.error('Font fetch failed:', err.message);
  process.exit(1);
});
